### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by webflo** [boxen/puppet-ruby#151]
@boxen/puppet-ruby-maintainers Could someone tag a new release? The last one is from May. Thanks!

**Comment by mislav** [comment]
There are no feature changes or bug fixes since last release: https://github.com/boxen/puppet-ruby/compare/8.5.6...9253aa5bb31c0bf3506ab445116e1f2d676ce313

The only changes were to `ruby::build::ensure` and `ruby::rbenv::ensure` default values, but it's easy to set those values in your own configuration without updating puppet-ruby.

We will tag a new release once there is a feature or bug fix to release.

Thanks for suggesting!
